/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PlaygroundGUI;

import java.awt.event.KeyEvent;

/**
 *
 * @author ISAIAH SHELL
 */
public class My_calculator extends javax.swing.JFrame {

    /**
     * Creates new form My_calculator
     */
    public My_calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton16 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        onn = new javax.swing.JRadioButton();
        off = new javax.swing.JRadioButton();
        zero = new javax.swing.JToggleButton();
        multiply = new javax.swing.JToggleButton();
        plus = new javax.swing.JToggleButton();
        sum = new javax.swing.JToggleButton();
        divide = new javax.swing.JToggleButton();
        minus = new javax.swing.JToggleButton();
        seven = new javax.swing.JToggleButton();
        four = new javax.swing.JToggleButton();
        one = new javax.swing.JToggleButton();
        twoZerro = new javax.swing.JToggleButton();
        two = new javax.swing.JToggleButton();
        three = new javax.swing.JToggleButton();
        five = new javax.swing.JToggleButton();
        six = new javax.swing.JToggleButton();
        eight = new javax.swing.JToggleButton();
        nine = new javax.swing.JToggleButton();
        dot = new javax.swing.JToggleButton();
        display_Pannel = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        displaySUM = new javax.swing.JLabel();
        back = new javax.swing.JToggleButton();
        clear = new javax.swing.JToggleButton();

        jToggleButton16.setBackground(new java.awt.Color(153, 153, 153));
        jToggleButton16.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jToggleButton16.setForeground(new java.awt.Color(0, 0, 0));
        jToggleButton16.setText("1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        onn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        onn.setForeground(new java.awt.Color(0, 0, 0));
        onn.setText("ON");
        onn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        onn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                onMethod(evt);
            }
        });

        off.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        off.setForeground(new java.awt.Color(0, 0, 0));
        off.setText("OFF");
        off.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        off.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                off_method(evt);
            }
        });
        off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offActionPerformed(evt);
            }
        });

        zero.setBackground(new java.awt.Color(153, 153, 153));
        zero.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        zero.setForeground(new java.awt.Color(0, 0, 0));
        zero.setText("0");
        zero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        zero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                zero(evt);
            }
        });

        multiply.setBackground(new java.awt.Color(153, 153, 153));
        multiply.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        multiply.setForeground(new java.awt.Color(0, 0, 0));
        multiply.setText("*");
        multiply.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiply.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                multiply(evt);
            }
        });

        plus.setBackground(new java.awt.Color(153, 153, 153));
        plus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        plus.setForeground(new java.awt.Color(0, 0, 0));
        plus.setText("+");
        plus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                plus(evt);
            }
        });

        sum.setBackground(new java.awt.Color(153, 153, 153));
        sum.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        sum.setForeground(new java.awt.Color(0, 0, 0));
        sum.setText("=");
        sum.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sum.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sum(evt);
            }
        });
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        divide.setBackground(new java.awt.Color(153, 153, 153));
        divide.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        divide.setForeground(new java.awt.Color(0, 0, 0));
        divide.setText("/");
        divide.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                divide(evt);
            }
        });

        minus.setBackground(new java.awt.Color(153, 153, 153));
        minus.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        minus.setForeground(new java.awt.Color(0, 0, 0));
        minus.setText("-");
        minus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minus(evt);
            }
        });

        seven.setBackground(new java.awt.Color(153, 153, 153));
        seven.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        seven.setForeground(new java.awt.Color(0, 0, 0));
        seven.setText("7");
        seven.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seven.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seven(evt);
            }
        });

        four.setBackground(new java.awt.Color(153, 153, 153));
        four.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        four.setForeground(new java.awt.Color(0, 0, 0));
        four.setText("4");
        four.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        four.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                four(evt);
            }
        });

        one.setBackground(new java.awt.Color(153, 153, 153));
        one.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        one.setForeground(new java.awt.Color(0, 0, 0));
        one.setText("1");
        one.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        one.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                one(evt);
            }
        });

        twoZerro.setBackground(new java.awt.Color(153, 153, 153));
        twoZerro.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        twoZerro.setForeground(new java.awt.Color(0, 0, 0));
        twoZerro.setText("00");
        twoZerro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twoZerro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twoZerro(evt);
            }
        });

        two.setBackground(new java.awt.Color(153, 153, 153));
        two.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        two.setForeground(new java.awt.Color(0, 0, 0));
        two.setText("2");
        two.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        two.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                two(evt);
            }
        });

        three.setBackground(new java.awt.Color(153, 153, 153));
        three.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        three.setForeground(new java.awt.Color(0, 0, 0));
        three.setText("3");
        three.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        three.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                three(evt);
            }
        });

        five.setBackground(new java.awt.Color(153, 153, 153));
        five.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        five.setForeground(new java.awt.Color(0, 0, 0));
        five.setText("5");
        five.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        five.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                five(evt);
            }
        });

        six.setBackground(new java.awt.Color(153, 153, 153));
        six.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        six.setForeground(new java.awt.Color(0, 0, 0));
        six.setText("6");
        six.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        six.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                six(evt);
            }
        });

        eight.setBackground(new java.awt.Color(153, 153, 153));
        eight.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        eight.setForeground(new java.awt.Color(0, 0, 0));
        eight.setText("8");
        eight.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        eight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eight(evt);
            }
        });

        nine.setBackground(new java.awt.Color(153, 153, 153));
        nine.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        nine.setForeground(new java.awt.Color(0, 0, 0));
        nine.setText("9");
        nine.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nine.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nine(evt);
            }
        });

        dot.setBackground(new java.awt.Color(153, 153, 153));
        dot.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dot.setForeground(new java.awt.Color(0, 0, 0));
        dot.setText(".");
        dot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dot(evt);
            }
        });

        display_Pannel.setBackground(new java.awt.Color(153, 153, 153));

        display.setBackground(new java.awt.Color(153, 153, 153));
        display.setFont(new java.awt.Font("Calibri Light", 1, 24)); // NOI18N
        display.setForeground(new java.awt.Color(0, 0, 0));
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setBorder(null);
        display.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        display.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numberinput(evt);
            }
        });

        displaySUM.setBackground(new java.awt.Color(255, 255, 255));
        displaySUM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        displaySUM.setForeground(new java.awt.Color(0, 0, 0));
        displaySUM.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout display_PannelLayout = new javax.swing.GroupLayout(display_Pannel);
        display_Pannel.setLayout(display_PannelLayout);
        display_PannelLayout.setHorizontalGroup(
            display_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
            .addComponent(displaySUM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        display_PannelLayout.setVerticalGroup(
            display_PannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(display_PannelLayout.createSequentialGroup()
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displaySUM, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        back.setBackground(new java.awt.Color(153, 153, 153));
        back.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 0));
        back.setText("<-");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back(evt);
            }
        });

        clear.setBackground(new java.awt.Color(153, 153, 153));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clear.setForeground(new java.awt.Color(0, 0, 0));
        clear.setText("C");
        clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(display_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(12, 12, 12)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(12, 12, 12)
                                            .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(twoZerro, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(off)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(onn)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(multiply, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(back, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(display_Pannel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(off)
                    .addComponent(onn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(twoZerro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(three, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 25, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(dot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divide, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiply, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_offActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumActionPerformed

    private void off_method(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_off_method
        // TODO add your handling code here:

        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        }

        display.setText("");
        displaySUM.setText("");

    }//GEN-LAST:event_off_method

    private void onMethod(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onMethod
        // TODO add your handling code here:
        if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
        }
    }//GEN-LAST:event_onMethod

    private void zero(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_zero
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + zero.getText();
            display.setText(number);
        }

    }//GEN-LAST:event_zero

    private void twoZerro(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twoZerro
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + twoZerro.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_twoZerro

    private void one(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_one
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + one.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_one

    private void two(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_two
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + two.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_two

    private void three(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_three
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + three.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_three

    private void four(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_four
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + four.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_four

    private void five(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_five
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + five.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_five

    private void six(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_six
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + six.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_six

    private void seven(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seven
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + seven.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_seven

    private void eight(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eight
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + eight.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_eight

    private void nine(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nine
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + nine.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_nine

    private void dot(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dot
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + dot.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_dot

    private void plus(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_plus
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + plus.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_plus

    private void minus(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minus
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + minus.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_minus

    private void divide(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_divide
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + divide.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_divide

    private void multiply(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_multiply
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            String number = display.getText() + multiply.getText();
            display.setText(number);
        }
    }//GEN-LAST:event_multiply

    private void back(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back
        // TODO add your handling code here:
        String backspace = null;
        if (display.getText().length() > 0) {
            StringBuilder clr = new StringBuilder(display.getText());
            clr.deleteCharAt(display.getText().length() - 1);
            backspace = clr.toString();
            display.setText(backspace);
        }
    }//GEN-LAST:event_back

    private void clear(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
            display.setText("");
            displaySUM.setText("");
        }

    }//GEN-LAST:event_clear

    private void numberinput(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numberinput
        // TODO add your handling code here:
        try {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

                String input = display.getText();
                String[] inputSum = input.split("\\+");
                String[] inputdivide = input.split("\\/");
                String[] inputmultiply = input.split("\\*");
                String[] inputsubtract = input.split("\\-");

                float sum;
                if (input.contains("+")) {
                    int firstnumber = Integer.parseInt(inputSum[0]);
                    int secondnumber = Integer.parseInt(inputSum[1]);

                    sum = firstnumber + secondnumber;
                    displaySUM.setText("" + sum);
                } else if (input.contains("/")) {
                    int firstnumber = Integer.parseInt(inputdivide[0]);
                    int secondnumber = Integer.parseInt(inputdivide[1]);

                    sum = firstnumber / secondnumber;
                    Double sumDouble = new Double(sum);
                    displaySUM.setText("" + sumDouble);
                } else if (input.contains("*")) {
                    int firstnumber = Integer.parseInt(inputmultiply[0]);
                    int secondnumber = Integer.parseInt(inputmultiply[1]);

                    sum = firstnumber * secondnumber;
                    displaySUM.setText("" + sum);
                } else if (input.contains("-")) {
                    int firstnumber = Integer.parseInt(inputsubtract[0]);
                    int secondnumber = Integer.parseInt(inputsubtract[1]);

                    sum = firstnumber - secondnumber;
                    displaySUM.setText("" + sum);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_numberinput

    private void sum(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sum
        // TODO add your handling code here:
        if (off.isSelected()) {
            onn.setSelected(false);
            display.setEditable(false);
            display.setText(" ");
            displaySUM.setText(" ");
        } else if (onn.isSelected()) {
            off.setSelected(false);
            display.setEditable(true);
//            String number = display.getText() + sum.getText();
            String input = display.getText();
            String[] inputSum = input.split("\\+");
            String[] inputdivide = input.split("\\/");
            String[] inputmultiply = input.split("\\*");
            String[] inputsubtract = input.split("\\-");

            float sum;
            if (input.contains("+")) {
                int firstnumber = Integer.parseInt(inputSum[0]);
                int secondnumber = Integer.parseInt(inputSum[1]);

                sum = firstnumber + secondnumber;
                displaySUM.setText("" + sum);
            } else if (input.contains("/")) {
                int firstnumber = Integer.parseInt(inputdivide[0]);
                int secondnumber = Integer.parseInt(inputdivide[1]);

                sum = firstnumber / secondnumber;
                Double sumDouble = new Double(sum);
                displaySUM.setText("" + sumDouble);
            } else if (input.contains("*")) {
                int firstnumber = Integer.parseInt(inputmultiply[0]);
                int secondnumber = Integer.parseInt(inputmultiply[1]);

                sum = firstnumber * secondnumber;
                displaySUM.setText("" + sum);
            } else if (input.contains("-")) {
                int firstnumber = Integer.parseInt(inputsubtract[0]);
                int secondnumber = Integer.parseInt(inputsubtract[1]);

                sum = firstnumber - secondnumber;
                displaySUM.setText("" + sum);
            }
        }
    }//GEN-LAST:event_sum

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(My_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(My_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(My_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(My_calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new My_calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton back;
    private javax.swing.JToggleButton clear;
    private javax.swing.JTextField display;
    private javax.swing.JLabel displaySUM;
    private javax.swing.JPanel display_Pannel;
    private javax.swing.JToggleButton divide;
    private javax.swing.JToggleButton dot;
    private javax.swing.JToggleButton eight;
    private javax.swing.JToggleButton five;
    private javax.swing.JToggleButton four;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton16;
    private javax.swing.JToggleButton minus;
    private javax.swing.JToggleButton multiply;
    private javax.swing.JToggleButton nine;
    private javax.swing.JRadioButton off;
    private javax.swing.JToggleButton one;
    private javax.swing.JRadioButton onn;
    private javax.swing.JToggleButton plus;
    private javax.swing.JToggleButton seven;
    private javax.swing.JToggleButton six;
    private javax.swing.JToggleButton sum;
    private javax.swing.JToggleButton three;
    private javax.swing.JToggleButton two;
    private javax.swing.JToggleButton twoZerro;
    private javax.swing.JToggleButton zero;
    // End of variables declaration//GEN-END:variables
}
